var searchData=
[
  ['b_20—_20manual_20installation_0',['Option B — Manual Installation',['../_installation.html#autotoc_md40',1,'']]],
  ['b_20create_20and_20assign_20abilities_20entirely_20in_20code_1',['B) Create and assign abilities entirely in code',['../ability_page.html#autotoc_md12',1,'']]],
  ['base_2',['Modular Architecture ( Dependency / Base )',['../_installation.html#autotoc_md38',1,'']]],
  ['basic_20example_3',['Basic Example',['../ability_page.html#autotoc_md16',1,'']]],
  ['be_20used_4',['Checking if an Ability Can Be Used',['../ability_page.html#autotoc_md17',1,'']]],
  ['best_20practices_5',['Best Practices',['../_a_p_i_page.html#autotoc_md59',1,'10. Best Practices'],['../buff_page.html#autotoc_md73',1,'11. Best Practices'],['../ability_page.html#autotoc_md27',1,'8. Best Practices'],['../effect_page.html#autotoc_md88',1,'8. Best Practices'],['../supply_page.html#autotoc_md115',1,'8. Best Practices'],['../status_page.html#autotoc_md103',1,'9. Best Practices']]],
  ['both_20approaches_6',['C) Mix both approaches',['../ability_page.html#autotoc_md13',1,'']]],
  ['buff_20api_7',['4. Buff API',['../_a_p_i_page.html#autotoc_md53',1,'']]],
  ['buff_20system_8',['Buff System',['../buff_page.html',1,'md__documentation_2_how-_to-_use']]],
  ['buff_20ticking_9',['7. Turn‑Based Buff Ticking',['../buff_page.html#autotoc_md69',1,'']]],
  ['buffapplied_10',['BuffApplied',['../class_ability_system_1_1_ability_system_a_p_i.html#ab689b9ec35e6db44ea5708befc8b699d',1,'AbilitySystem::AbilitySystemAPI']]],
  ['buffdata_11',['BuffData',['../buff_page.html#autotoc_md64',1,'2. BuffData'],['../class_ability_system_1_1_buff_1_1_buff_data.html',1,'AbilitySystem.Buff.BuffData']]],
  ['buffinstance_12',['BuffInstance',['../buff_page.html#autotoc_md66',1,'4. BuffInstance'],['../class_ability_system_1_1_buff_1_1_buff_instance.html',1,'AbilitySystem.Buff.BuffInstance'],['../class_ability_system_1_1_buff_1_1_buff_instance.html#ad88715d6c0331abf7e1589f32fe87cf2',1,'AbilitySystem.Buff.BuffInstance.BuffInstance()']]],
  ['buffinstances_13',['buffInstances',['../class_ability_system_1_1_buff_1_1_buff_manager.html#af724bc6f06217e36f29d52d6e99b7aa8',1,'AbilitySystem::Buff::BuffManager']]],
  ['buffmanager_14',['BuffManager',['../buff_page.html#autotoc_md68',1,'6. BuffManager'],['../class_ability_system_1_1_buff_1_1_buff_manager.html',1,'AbilitySystem.Buff.BuffManager'],['../class_ability_system_1_1_buff_1_1_buff_manager.html#a2153dae856d8bcdc532a1a3f090ce2bc',1,'AbilitySystem.Buff.BuffManager.BuffManager()']]],
  ['buffmanager_15',['buffManager',['../interface_ability_system_1_1_buff_1_1_i_buff_container.html#adb4a4d6eee1940e5bc3de1bfc68a7aa3',1,'AbilitySystem::Buff::IBuffContainer']]],
  ['buffremoved_16',['BuffRemoved',['../class_ability_system_1_1_ability_system_a_p_i.html#aa1b2fed7247a5b624cdf3de11ffddcbb',1,'AbilitySystem::AbilitySystemAPI']]],
  ['buffs_17',['Buffs',['../buff_page.html#autotoc_md63',1,'1. Understanding Buffs'],['../buff_page.html#autotoc_md72',1,'10. Creating Custom Buffs'],['../buff_page.html#autotoc_md62',1,'How‑To: Buffs']]],
  ['buffs_20via_20the_20api_18',['8. Applying and Removing Buffs via the API',['../buff_page.html#autotoc_md70',1,'']]],
  ['buffs_20with_20units_19',['9. Integrating Buffs With Units',['../buff_page.html#autotoc_md71',1,'']]],
  ['buffstatusdata_20',['BuffStatusData',['../class_ability_system_1_1_status_1_1_buff_status_data.html',1,'AbilitySystem::Status']]],
  ['buffstatusinstance_21',['BuffStatusInstance',['../class_ability_system_1_1_status_1_1_buff_status_instance.html',1,'AbilitySystem.Status.BuffStatusInstance'],['../class_ability_system_1_1_status_1_1_buff_status_instance.html#ae44b17365abc5a8c3b71314102a12872',1,'AbilitySystem.Status.BuffStatusInstance.BuffStatusInstance()']]],
  ['built‑in_20effects_22',['4. Built‑In Effects',['../effect_page.html#autotoc_md84',1,'']]],
  ['built‑in_20statuses_23',['6. Built‑In Statuses',['../status_page.html#autotoc_md100',1,'']]]
];
