var searchData=
[
  ['b_20—_20manual_20installation_0',['Option B — Manual Installation',['../_installation.html#autotoc_md40',1,'']]],
  ['b_20create_20and_20assign_20abilities_20entirely_20in_20code_1',['B) Create and assign abilities entirely in code',['../ability_page.html#autotoc_md12',1,'']]],
  ['base_2',['Modular Architecture ( Dependency / Base )',['../_installation.html#autotoc_md38',1,'']]],
  ['basic_20example_3',['Basic Example',['../ability_page.html#autotoc_md16',1,'']]],
  ['be_20used_4',['Checking if an Ability Can Be Used',['../ability_page.html#autotoc_md17',1,'']]],
  ['best_20practices_5',['Best Practices',['../buff_page.html#autotoc_md60',1,'11. Best Practices'],['../ability_page.html#autotoc_md27',1,'8. Best Practices'],['../effect_page.html#autotoc_md75',1,'8. Best Practices'],['../supply_page.html#autotoc_md102',1,'8. Best Practices'],['../status_page.html#autotoc_md90',1,'9. Best Practices']]],
  ['both_20approaches_6',['C) Mix both approaches',['../ability_page.html#autotoc_md13',1,'']]],
  ['buff_20system_7',['Buff System',['../buff_page.html',1,'md__documentation_2_how-_to-_use']]],
  ['buff_20ticking_8',['7. Turn‑Based Buff Ticking',['../buff_page.html#autotoc_md56',1,'']]],
  ['buffapplied_9',['BuffApplied',['../class_ability_system_1_1_ability_system_a_p_i.html#ab689b9ec35e6db44ea5708befc8b699d',1,'AbilitySystem::AbilitySystemAPI']]],
  ['buffdata_10',['BuffData',['../buff_page.html#autotoc_md51',1,'2. BuffData'],['../class_ability_system_1_1_buff_1_1_buff_data.html',1,'AbilitySystem.Buff.BuffData']]],
  ['buffinstance_11',['BuffInstance',['../buff_page.html#autotoc_md53',1,'4. BuffInstance'],['../class_ability_system_1_1_buff_1_1_buff_instance.html',1,'AbilitySystem.Buff.BuffInstance'],['../class_ability_system_1_1_buff_1_1_buff_instance.html#ad88715d6c0331abf7e1589f32fe87cf2',1,'AbilitySystem.Buff.BuffInstance.BuffInstance()']]],
  ['buffinstances_12',['buffInstances',['../class_ability_system_1_1_buff_1_1_buff_manager.html#af724bc6f06217e36f29d52d6e99b7aa8',1,'AbilitySystem::Buff::BuffManager']]],
  ['buffmanager_13',['BuffManager',['../buff_page.html#autotoc_md55',1,'6. BuffManager'],['../class_ability_system_1_1_buff_1_1_buff_manager.html',1,'AbilitySystem.Buff.BuffManager'],['../class_ability_system_1_1_buff_1_1_buff_manager.html#a2153dae856d8bcdc532a1a3f090ce2bc',1,'AbilitySystem.Buff.BuffManager.BuffManager()']]],
  ['buffmanager_14',['buffManager',['../interface_ability_system_1_1_buff_1_1_i_buff_container.html#adb4a4d6eee1940e5bc3de1bfc68a7aa3',1,'AbilitySystem::Buff::IBuffContainer']]],
  ['buffremoved_15',['BuffRemoved',['../class_ability_system_1_1_ability_system_a_p_i.html#aa1b2fed7247a5b624cdf3de11ffddcbb',1,'AbilitySystem::AbilitySystemAPI']]],
  ['buffs_16',['Buffs',['../buff_page.html#autotoc_md50',1,'1. Understanding Buffs'],['../buff_page.html#autotoc_md59',1,'10. Creating Custom Buffs'],['../buff_page.html#autotoc_md49',1,'How‑To: Buffs']]],
  ['buffs_20via_20the_20api_17',['8. Applying and Removing Buffs via the API',['../buff_page.html#autotoc_md57',1,'']]],
  ['buffs_20with_20units_18',['9. Integrating Buffs With Units',['../buff_page.html#autotoc_md58',1,'']]],
  ['buffstatusdata_19',['BuffStatusData',['../class_ability_system_1_1_status_1_1_buff_status_data.html',1,'AbilitySystem::Status']]],
  ['buffstatusinstance_20',['BuffStatusInstance',['../class_ability_system_1_1_status_1_1_buff_status_instance.html',1,'AbilitySystem.Status.BuffStatusInstance'],['../class_ability_system_1_1_status_1_1_buff_status_instance.html#ae44b17365abc5a8c3b71314102a12872',1,'AbilitySystem.Status.BuffStatusInstance.BuffStatusInstance()']]],
  ['built‑in_20effects_21',['4. Built‑In Effects',['../effect_page.html#autotoc_md71',1,'']]],
  ['built‑in_20statuses_22',['6. Built‑In Statuses',['../status_page.html#autotoc_md87',1,'']]]
];
