var searchData=
[
  ['raising_20an_20event_0',['Raising an Event',['../_how-_to-_use.html#autotoc_md50',1,'']]],
  ['range_1',['range',['../class_ability_system_1_1_ability_1_1_ability_data.html#afd49d12f44914eddf20501aace3f6e6e',1,'AbilitySystem::Ability::AbilityData']]],
  ['reading_2',['Reading',['../index.html#autotoc_md28',1,'Thank You For Reading'],['../_installation.html#autotoc_md34',1,'Thank You For Reading'],['../_how-_to-_use.html#autotoc_md60',1,'Thank You For Reading']]],
  ['readings_3',['Readings',['../index.html#autotoc_md29',1,'&lt;span class=&quot;tt&quot;&gt;Suggested Readings&lt;/span&gt;'],['../_installation.html#autotoc_md35',1,'&lt;span class=&quot;tt&quot;&gt;Suggested Readings&lt;/span&gt;'],['../_how-_to-_use.html#autotoc_md61',1,'&lt;span class=&quot;tt&quot;&gt;Suggested Readings&lt;/span&gt;']]],
  ['references_4',['How to Use Data References',['../_how-_to-_use.html#autotoc_md43',1,'']]],
  ['regenerationstatusdata_5',['RegenerationStatusData',['../class_ability_system_1_1_status_1_1_regeneration_status_data.html',1,'AbilitySystem::Status']]],
  ['regenerationstatusinstance_6',['RegenerationStatusInstance',['../class_ability_system_1_1_status_1_1_regeneration_status_instance.html',1,'AbilitySystem.Status.RegenerationStatusInstance'],['../class_ability_system_1_1_status_1_1_regeneration_status_instance.html#aa08dc2cfa92bbe321a94bebed9e60ded',1,'AbilitySystem.Status.RegenerationStatusInstance.RegenerationStatusInstance()']]],
  ['removebuff_7',['RemoveBuff',['../class_ability_system_1_1_ability_system_a_p_i.html#ac2e73a6a5ef4fc3e794b227c00556c17',1,'AbilitySystem.AbilitySystemAPI.RemoveBuff(IBuffContainer aTargetUnit, BuffInstance buffInstance)'],['../class_ability_system_1_1_ability_system_a_p_i.html#a8ee66605dbd1ac6bc31bdc8d4a51da73',1,'AbilitySystem.AbilitySystemAPI.RemoveBuff(IBuffContainer aTargetUnit, BuffData buffInstance)'],['../class_ability_system_1_1_buff_1_1_buff_manager.html#afdaab356842dacc894bc23745f871562',1,'AbilitySystem.Buff.BuffManager.RemoveBuff(BuffInstance buffInstance)'],['../class_ability_system_1_1_buff_1_1_buff_manager.html#a0ffebc4d2ae18dd393f0078296d75e25',1,'AbilitySystem.Buff.BuffManager.RemoveBuff(BuffData buffData)']]],
  ['removed_8',['Removed',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md9',1,'Removed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md17',1,'Removed']]],
  ['removeeffect_9',['RemoveEffect',['../class_ability_system_1_1_status_1_1_status_manager.html#aa284e03c2cb3bd3a5905c578a7c662a7',1,'AbilitySystem.Status.StatusManager.RemoveEffect(StatusData effect)'],['../class_ability_system_1_1_status_1_1_status_manager.html#a05e7fc1ac16d424acc0e93d3d541fd99',1,'AbilitySystem.Status.StatusManager.RemoveEffect(StatusInstance instance)']]],
  ['removestatus_10',['RemoveStatus',['../class_ability_system_1_1_ability_system_a_p_i.html#ada82755955384d042d565c9131d68578',1,'AbilitySystem.AbilitySystemAPI.RemoveStatus(IStatusContainer aTargetUnit, StatusData data)'],['../class_ability_system_1_1_ability_system_a_p_i.html#ad3144963933a57fc56d1f8bdf5671ce1',1,'AbilitySystem.AbilitySystemAPI.RemoveStatus(IStatusContainer aTargetUnit, StatusInstance aTargetInstance)']]],
  ['result_11',['result',['../class_ability_system_1_1_status_1_1_mix_rule.html#aea37803d3ce60fb45c72f0350c25a6f5',1,'AbilitySystem::Status::MixRule']]]
];
