var searchData=
[
  ['ibuffcontainer_0',['IBuffContainer',['../buff_page.html#autotoc_md54',1,'5. IBuffContainer'],['../interface_ability_system_1_1_buff_1_1_i_buff_container.html',1,'AbilitySystem.Buff.IBuffContainer']]],
  ['id_1',['id',['../class_ability_system_1_1_ability_1_1_ability_data.html#a1730f7a1a8a224bbe2967387d0c3aceb',1,'AbilitySystem.Ability.AbilityData.id'],['../class_ability_system_1_1_buff_1_1_buff_data.html#a07a3c927d81caeda17ce266a83e53567',1,'AbilitySystem.Buff.BuffData.id'],['../class_ability_system_1_1_status_1_1_status_data.html#a1e87b42f1b9fb438d989f9a067031ec9',1,'AbilitySystem.Status.StatusData.id'],['../class_ability_system_1_1_supplies_1_1_supply.html#a41af1e8a16fe4ef39a5cff75d7899827',1,'AbilitySystem.Supplies.Supply.id']]],
  ['if_20an_20ability_20can_20be_20used_2',['Checking if an Ability Can Be Used',['../ability_page.html#autotoc_md17',1,'']]],
  ['in_20code_3',['B) Create and assign abilities entirely in code',['../ability_page.html#autotoc_md12',1,'']]],
  ['in_20the_20inspector_4',['4. Creating Supplies in the Inspector',['../supply_page.html#autotoc_md98',1,'']]],
  ['in_20the_20inspector_20and_20create_20instances_20at_20runtime_5',['A) Assign AbilityData in the inspector and create instances at runtime',['../ability_page.html#autotoc_md11',1,'']]],
  ['initial_20release_6',['[1.0.0] - Initial Release',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md3',1,'']]],
  ['inspector_7',['4. Creating Supplies in the Inspector',['../supply_page.html#autotoc_md98',1,'']]],
  ['inspector_20and_20create_20instances_20at_20runtime_8',['A) Assign AbilityData in the inspector and create instances at runtime',['../ability_page.html#autotoc_md11',1,'']]],
  ['install_9',['Manual Install',['../_installation.html#autotoc_md45',1,'']]],
  ['install_20via_20git_20url_20unity_20package_20manager_10',['Option A — Install via Git URL (Unity Package Manager)',['../_installation.html#autotoc_md39',1,'']]],
  ['installation_11',['Installation',['../_installation.html',1,'Installation'],['../_installation.html#autotoc_md40',1,'Option B — Manual Installation']]],
  ['installing_20the_20tactics_20ability_20system_20package_20_3a_12',['Installing the Tactics Ability System Package :',['../_installation.html#autotoc_md41',1,'']]],
  ['instance_13',['Instance',['../class_ability_system_1_1_ability_system_a_p_i.html#a6f8d89ca847f9ae4f24e38a4877493dd',1,'AbilitySystem::AbilitySystemAPI']]],
  ['instance_14',['instance',['../class_ability_system_1_1_status_1_1_status_effect_mixer.html#adc83a0f032adcbe755d2264ed9e0f050',1,'AbilitySystem::Status::StatusEffectMixer']]],
  ['instances_15',['3. Creating Ability Instances',['../ability_page.html#autotoc_md9',1,'']]],
  ['instances_20at_20runtime_16',['A) Assign AbilityData in the inspector and create instances at runtime',['../ability_page.html#autotoc_md11',1,'']]],
  ['integrate_20with_20abilities_17',['3. How Effects Integrate With Abilities',['../effect_page.html#autotoc_md70',1,'']]],
  ['integrating_20abilities_20into_20gameplay_18',['6. Integrating Abilities Into Gameplay',['../ability_page.html#autotoc_md19',1,'']]],
  ['integrating_20buffs_20with_20units_19',['9. Integrating Buffs With Units',['../buff_page.html#autotoc_md58',1,'']]],
  ['integrating_20effects_20with_20ui_20vfx_20and_20audio_20',['7. Integrating Effects With UI, VFX, and Audio',['../effect_page.html#autotoc_md74',1,'']]],
  ['integrating_20statuses_20into_20gameplay_21',['8. Integrating Statuses Into Gameplay',['../status_page.html#autotoc_md89',1,'']]],
  ['integrating_20supplies_20with_20abilities_22',['3. Integrating Supplies With Abilities',['../supply_page.html#autotoc_md97',1,'']]],
  ['into_20gameplay_23',['Into Gameplay',['../ability_page.html#autotoc_md19',1,'6. Integrating Abilities Into Gameplay'],['../status_page.html#autotoc_md89',1,'8. Integrating Statuses Into Gameplay']]],
  ['isactivatable_24',['IsActivatable',['../class_ability_system_1_1_ability_system_a_p_i.html#ae500c351b3e72b01d205be90d4be26f2',1,'AbilitySystem::AbilitySystemAPI']]],
  ['iscomponentofactive_25',['IsComponentOfActive',['../class_ability_system_1_1_status_1_1_status_manager.html#a5fdbc900cfd8d370d24addefb9699264',1,'AbilitySystem::Status::StatusManager']]],
  ['istatuscontainer_26',['IStatusContainer',['../interface_ability_system_1_1_status_1_1_i_status_container.html',1,'AbilitySystem::Status']]],
  ['it_27',['Step 4 — Execute It',['../ability_page.html#autotoc_md26',1,'']]],
  ['iunit_28',['IUnit',['../interface_ability_system_1_1_i_unit.html',1,'AbilitySystem']]]
];
