var searchData=
[
  ['scripttemplates_0',['ScriptTemplates',['../class_ability_system_1_1_editor_1_1_script_templates.html',1,'AbilitySystem::Editor']]],
  ['simple_20ability_1',['7. Example: Creating a Simple Ability',['../ability_page.html#autotoc_md22',1,'']]],
  ['spawnobjecteffect_2',['SpawnObjectEffect',['../class_ability_system_1_1_ability_1_1_spawn_object_effect.html',1,'AbilitySystem::Ability']]],
  ['start_20turn_20end_3',['Turn Start / Turn End',['../ability_page.html#autotoc_md20',1,'']]],
  ['statmodifier_4',['StatModifier',['../struct_ability_system_1_1_buff_1_1_stat_modifier.html',1,'AbilitySystem::Buff']]],
  ['statmodifiertype_5',['StatModifierType',['../namespace_ability_system_1_1_buff.html#ad34d78be7a21eb408125193ce681dd6e',1,'AbilitySystem::Buff']]],
  ['status_20system_6',['Status System',['../status_page.html',1,'md__documentation_2_how-_to-_use']]],
  ['statusactivated_7',['StatusActivated',['../class_ability_system_1_1_ability_system_a_p_i.html#a4aecefd38069fb55cf8251a2b2be84ef',1,'AbilitySystem::AbilitySystemAPI']]],
  ['statusapplied_8',['StatusApplied',['../class_ability_system_1_1_ability_system_a_p_i.html#a77b35cc2fc0bc86dedcbe21f7c30d0b9',1,'AbilitySystem::AbilitySystemAPI']]],
  ['statusdata_9',['StatusData',['../class_ability_system_1_1_status_1_1_status_data.html',1,'AbilitySystem::Status']]],
  ['statuseffectmixer_10',['StatusEffectMixer',['../class_ability_system_1_1_status_1_1_status_effect_mixer.html',1,'AbilitySystem::Status']]],
  ['statuseffectmixingdatabase_11',['StatusEffectMixingDatabase',['../class_ability_system_1_1_status_1_1_status_effect_mixing_database.html',1,'AbilitySystem::Status']]],
  ['statuseffectmixingdatabaseeditor_12',['StatusEffectMixingDatabaseEditor',['../class_ability_system_1_1_editor_1_1_status_effect_mixing_database_editor.html',1,'AbilitySystem::Editor']]],
  ['statusinstance_13',['StatusInstance',['../class_ability_system_1_1_status_1_1_status_instance.html',1,'AbilitySystem.Status.StatusInstance'],['../class_ability_system_1_1_status_1_1_status_instance.html#abf210a59efb42e95afb9275caa52f756',1,'AbilitySystem.Status.StatusInstance.StatusInstance()'],['../class_ability_system_1_1_status_1_1_status_instance.html#aed8a36cff5a9124d637f92a0db8cd21f',1,'AbilitySystem.Status.StatusInstance.StatusInstance(StatusData aData)']]],
  ['statusmanager_14',['StatusManager',['../class_ability_system_1_1_status_1_1_status_manager.html',1,'AbilitySystem.Status.StatusManager'],['../interface_ability_system_1_1_status_1_1_i_status_container.html#a6f3bb8b1c64d440d74f4a03b8a919f4f',1,'AbilitySystem.Status.IStatusContainer.StatusManager'],['../class_ability_system_1_1_status_1_1_status_manager.html#ab696849ea83cdf280637c51497feb845',1,'AbilitySystem.Status.StatusManager.StatusManager()']]],
  ['statusremoved_15',['StatusRemoved',['../class_ability_system_1_1_ability_system_a_p_i.html#af7a9fd6d3b9aa01b9bff5bb2e1de8108',1,'AbilitySystem::AbilitySystemAPI']]],
  ['step_201_20—_20create_20an_20effect_16',['Step 1 — Create an Effect',['../ability_page.html#autotoc_md23',1,'']]],
  ['step_202_20—_20create_20an_20abilitydata_17',['Step 2 — Create an AbilityData',['../ability_page.html#autotoc_md24',1,'']]],
  ['step_203_20—_20assign_20ability_20to_20a_20unit_18',['Step 3 — Assign Ability to a Unit',['../ability_page.html#autotoc_md25',1,'']]],
  ['step_204_20—_20execute_20it_19',['Step 4 — Execute It',['../ability_page.html#autotoc_md26',1,'']]],
  ['storing_20abilities_20on_20units_20',['4. Storing Abilities on Units',['../ability_page.html#autotoc_md14',1,'']]],
  ['structure_21',['Package Structure',['../index.html#autotoc_md31',1,'']]],
  ['subeffects_22',['subEffects',['../class_ability_system_1_1_status_1_1_composite_status_data.html#a27ceace14a95bff2c8e0a0927d5f7db5',1,'AbilitySystem::Status::CompositeStatusData']]],
  ['suggested_20readings_23',['Suggested Readings',['../index.html#autotoc_md34',1,'&lt;span class=&quot;tt&quot;&gt;Suggested Readings&lt;/span&gt;'],['../_installation.html#autotoc_md46',1,'&lt;span class=&quot;tt&quot;&gt;Suggested Readings&lt;/span&gt;'],['../md__documentation_2_how-_to-_use.html#autotoc_md51',1,'&lt;span class=&quot;tt&quot;&gt;Suggested Readings&lt;/span&gt;']]],
  ['summary_24',['9. Summary',['../ability_page.html#autotoc_md28',1,'']]],
  ['supplies_25',['supplies',['../class_ability_system_1_1_ability_1_1_ability_data.html#aabfaa426d876e75d93e1cc33f41f8305',1,'AbilitySystem::Ability::AbilityData']]],
  ['supply_26',['Supply',['../class_ability_system_1_1_supplies_1_1_supply.html',1,'AbilitySystem::Supplies']]],
  ['supply_20system_27',['Supply System',['../supply_page.html',1,'md__documentation_2_how-_to-_use']]],
  ['support_28',['Support',['../namespace_ability_system_1_1_ability.html#a9f71bffef370480022c5fbc45907bed2adb5eb84117d06047c97c9a0191b5fffe',1,'AbilitySystem::Ability']]],
  ['system_29',['System',['../ability_page.html',1,'Ability System'],['../_a_p_i_page.html',1,'API System'],['../buff_page.html',1,'Buff System'],['../effect_page.html',1,'Effect System'],['../status_page.html',1,'Status System'],['../supply_page.html',1,'Supply System'],['../index.html',1,'Tactics Ability System']]],
  ['system_20package_20_3a_30',['Installing the Tactics Ability System Package :',['../_installation.html#autotoc_md39',1,'']]]
];
