var searchData=
[
  ['c_20mix_20both_20approaches_0',['C) Mix both approaches',['../ability_page.html#autotoc_md13',1,'']]],
  ['can_20be_20used_1',['Checking if an Ability Can Be Used',['../ability_page.html#autotoc_md17',1,'']]],
  ['chaining_20effects_2',['6. Chaining Effects',['../effect_page.html#autotoc_md73',1,'']]],
  ['changelog_3',['Changelog',['../md__c_h_a_n_g_e_l_o_g.html',1,'']]],
  ['checking_20if_20an_20ability_20can_20be_20used_4',['Checking if an Ability Can Be Used',['../ability_page.html#autotoc_md17',1,'']]],
  ['code_5',['B) Create and assign abilities entirely in code',['../ability_page.html#autotoc_md12',1,'']]],
  ['create_20an_20abilitydata_6',['Step 2 — Create an AbilityData',['../ability_page.html#autotoc_md24',1,'']]],
  ['create_20an_20effect_7',['Step 1 — Create an Effect',['../ability_page.html#autotoc_md23',1,'']]],
  ['create_20and_20assign_20abilities_20entirely_20in_20code_8',['B) Create and assign abilities entirely in code',['../ability_page.html#autotoc_md12',1,'']]],
  ['create_20instances_20at_20runtime_9',['A) Assign AbilityData in the inspector and create instances at runtime',['../ability_page.html#autotoc_md11',1,'']]],
  ['creating_20a_20simple_20ability_10',['7. Example: Creating a Simple Ability',['../ability_page.html#autotoc_md22',1,'']]],
  ['creating_20ability_20instances_11',['3. Creating Ability Instances',['../ability_page.html#autotoc_md9',1,'']]],
  ['creating_20an_20ability_12',['2. Creating an Ability',['../ability_page.html#autotoc_md7',1,'']]],
  ['creating_20an_20effect_13',['2. Creating an Effect',['../effect_page.html#autotoc_md69',1,'']]],
  ['creating_20custom_20buffs_14',['10. Creating Custom Buffs',['../buff_page.html#autotoc_md59',1,'']]],
  ['creating_20custom_20effects_15',['5. Creating Custom Effects',['../effect_page.html#autotoc_md72',1,'']]],
  ['creating_20custom_20statuses_16',['7. Creating Custom Statuses',['../status_page.html#autotoc_md88',1,'']]],
  ['credits_17',['Credits',['../md__documentation_2_credits.html',1,'']]],
  ['css_18',['CSS',['../md__documentation_2_credits.html#autotoc_md66',1,'Doxygen Awesome CSS'],['../md__third_01_party_01_notices.html#autotoc_md95',1,'Doxygen Awesome CSS']]],
  ['custom_20buffs_19',['10. Creating Custom Buffs',['../buff_page.html#autotoc_md59',1,'']]],
  ['custom_20effects_20',['5. Creating Custom Effects',['../effect_page.html#autotoc_md72',1,'']]],
  ['custom_20statuses_21',['7. Creating Custom Statuses',['../status_page.html#autotoc_md88',1,'']]]
];
