var searchData=
[
  ['a_20—_20install_20via_20git_20url_20unity_20package_20manager_0',['Option A — Install via Git URL (Unity Package Manager)',['../_installation.html#autotoc_md37',1,'']]],
  ['a_20assign_20abilitydata_20in_20the_20inspector_20and_20create_20instances_20at_20runtime_1',['A) Assign AbilityData in the inspector and create instances at runtime',['../ability_page.html#autotoc_md11',1,'']]],
  ['a_20simple_20ability_2',['7. Example: Creating a Simple Ability',['../ability_page.html#autotoc_md22',1,'']]],
  ['a_20unit_3',['Step 3 — Assign Ability to a Unit',['../ability_page.html#autotoc_md25',1,'']]],
  ['abilities_4',['Abilities',['../ability_page.html#autotoc_md6',1,'1. Understanding Abilities'],['../ability_page.html#autotoc_md5',1,'How‑To: Abilities']]],
  ['abilities_20entirely_20in_20code_5',['B) Create and assign abilities entirely in code',['../ability_page.html#autotoc_md12',1,'']]],
  ['abilities_20into_20gameplay_6',['6. Integrating Abilities Into Gameplay',['../ability_page.html#autotoc_md19',1,'']]],
  ['abilities_20on_20units_7',['4. Storing Abilities on Units',['../ability_page.html#autotoc_md14',1,'']]],
  ['ability_8',['Ability',['../ability_page.html#autotoc_md7',1,'2. Creating an Ability'],['../ability_page.html#autotoc_md15',1,'5. Executing an Ability'],['../ability_page.html#autotoc_md22',1,'7. Example: Creating a Simple Ability']]],
  ['ability_20can_20be_20used_9',['Checking if an Ability Can Be Used',['../ability_page.html#autotoc_md17',1,'']]],
  ['ability_20fields_10',['Ability Fields',['../ability_page.html#autotoc_md8',1,'']]],
  ['ability_20instances_11',['3. Creating Ability Instances',['../ability_page.html#autotoc_md9',1,'']]],
  ['ability_20system_12',['Ability System',['../ability_page.html',1,'Ability System'],['../index.html',1,'Tactics Ability System']]],
  ['ability_20system_20package_20_3a_13',['Installing the Tactics Ability System Package :',['../_installation.html#autotoc_md39',1,'']]],
  ['ability_20to_20a_20unit_14',['Step 3 — Assign Ability to a Unit',['../ability_page.html#autotoc_md25',1,'']]],
  ['abilitydata_15',['Step 2 — Create an AbilityData',['../ability_page.html#autotoc_md24',1,'']]],
  ['abilitydata_20in_20the_20inspector_20and_20create_20instances_20at_20runtime_16',['A) Assign AbilityData in the inspector and create instances at runtime',['../ability_page.html#autotoc_md11',1,'']]],
  ['about_17',['About',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md1',1,'']]],
  ['added_18',['Added',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md4',1,'']]],
  ['an_20ability_19',['an Ability',['../ability_page.html#autotoc_md7',1,'2. Creating an Ability'],['../ability_page.html#autotoc_md15',1,'5. Executing an Ability']]],
  ['an_20ability_20can_20be_20used_20',['Checking if an Ability Can Be Used',['../ability_page.html#autotoc_md17',1,'']]],
  ['an_20abilitydata_21',['Step 2 — Create an AbilityData',['../ability_page.html#autotoc_md24',1,'']]],
  ['an_20effect_22',['Step 1 — Create an Effect',['../ability_page.html#autotoc_md23',1,'']]],
  ['and_20assign_20abilities_20entirely_20in_20code_23',['B) Create and assign abilities entirely in code',['../ability_page.html#autotoc_md12',1,'']]],
  ['and_20create_20instances_20at_20runtime_24',['A) Assign AbilityData in the inspector and create instances at runtime',['../ability_page.html#autotoc_md11',1,'']]],
  ['api_20system_25',['API System',['../_a_p_i_page.html',1,'md__documentation_2_how-_to-_use']]],
  ['approaches_26',['C) Mix both approaches',['../ability_page.html#autotoc_md13',1,'']]],
  ['architecture_27',['Modular Architecture',['../md__third_01_party_01_notices.html#autotoc_md54',1,'']]],
  ['architecture_20dependency_20base_28',['Modular Architecture ( Dependency / Base )',['../_installation.html#autotoc_md36',1,'']]],
  ['assign_20abilities_20entirely_20in_20code_29',['B) Create and assign abilities entirely in code',['../ability_page.html#autotoc_md12',1,'']]],
  ['assign_20ability_20to_20a_20unit_30',['Step 3 — Assign Ability to a Unit',['../ability_page.html#autotoc_md25',1,'']]],
  ['assign_20abilitydata_20in_20the_20inspector_20and_20create_20instances_20at_20runtime_31',['A) Assign AbilityData in the inspector and create instances at runtime',['../ability_page.html#autotoc_md11',1,'']]],
  ['at_20runtime_32',['A) Assign AbilityData in the inspector and create instances at runtime',['../ability_page.html#autotoc_md11',1,'']]],
  ['awesome_20css_33',['Awesome CSS',['../md__documentation_2_credits.html#autotoc_md49',1,'Doxygen Awesome CSS'],['../md__third_01_party_01_notices.html#autotoc_md53',1,'Doxygen Awesome CSS']]]
];
