var searchData=
[
  ['c_20mix_20both_20approaches_0',['C) Mix both approaches',['../ability_page.html#autotoc_md13',1,'']]],
  ['can_20be_20used_1',['Checking if an Ability Can Be Used',['../ability_page.html#autotoc_md17',1,'']]],
  ['chaining_20effects_2',['6. Chaining Effects',['../effect_page.html#autotoc_md73',1,'']]],
  ['changelog_3',['Changelog',['../md__c_h_a_n_g_e_l_o_g.html',1,'']]],
  ['checking_20if_20an_20ability_20can_20be_20used_4',['Checking if an Ability Can Be Used',['../ability_page.html#autotoc_md17',1,'']]],
  ['class_5',['2. Supply Class',['../supply_page.html#autotoc_md96',1,'']]],
  ['code_6',['B) Create and assign abilities entirely in code',['../ability_page.html#autotoc_md12',1,'']]],
  ['connecting_20supplies_20to_20your_20resource_20system_7',['5. Connecting Supplies to Your Resource System',['../supply_page.html#autotoc_md99',1,'']]],
  ['cost_8',['Cost',['../supply_page.html#autotoc_md100',1,'6. Example: Mana Cost'],['../supply_page.html#autotoc_md101',1,'7. Example: Ammo Cost']]],
  ['create_20an_20abilitydata_9',['Step 2 — Create an AbilityData',['../ability_page.html#autotoc_md24',1,'']]],
  ['create_20an_20effect_10',['Step 1 — Create an Effect',['../ability_page.html#autotoc_md23',1,'']]],
  ['create_20and_20assign_20abilities_20entirely_20in_20code_11',['B) Create and assign abilities entirely in code',['../ability_page.html#autotoc_md12',1,'']]],
  ['create_20instances_20at_20runtime_12',['A) Assign AbilityData in the inspector and create instances at runtime',['../ability_page.html#autotoc_md11',1,'']]],
  ['creating_20a_20simple_20ability_13',['7. Example: Creating a Simple Ability',['../ability_page.html#autotoc_md22',1,'']]],
  ['creating_20ability_20instances_14',['3. Creating Ability Instances',['../ability_page.html#autotoc_md9',1,'']]],
  ['creating_20an_20ability_15',['2. Creating an Ability',['../ability_page.html#autotoc_md7',1,'']]],
  ['creating_20an_20effect_16',['2. Creating an Effect',['../effect_page.html#autotoc_md69',1,'']]],
  ['creating_20custom_20buffs_17',['10. Creating Custom Buffs',['../buff_page.html#autotoc_md59',1,'']]],
  ['creating_20custom_20effects_18',['5. Creating Custom Effects',['../effect_page.html#autotoc_md72',1,'']]],
  ['creating_20custom_20statuses_19',['7. Creating Custom Statuses',['../status_page.html#autotoc_md88',1,'']]],
  ['creating_20supplies_20in_20the_20inspector_20',['4. Creating Supplies in the Inspector',['../supply_page.html#autotoc_md98',1,'']]],
  ['credits_21',['Credits',['../md__documentation_2_credits.html',1,'']]],
  ['css_22',['CSS',['../md__documentation_2_credits.html#autotoc_md66',1,'Doxygen Awesome CSS'],['../md__third_01_party_01_notices.html#autotoc_md105',1,'Doxygen Awesome CSS']]],
  ['custom_20buffs_23',['10. Creating Custom Buffs',['../buff_page.html#autotoc_md59',1,'']]],
  ['custom_20effects_24',['5. Creating Custom Effects',['../effect_page.html#autotoc_md72',1,'']]],
  ['custom_20statuses_25',['7. Creating Custom Statuses',['../status_page.html#autotoc_md88',1,'']]]
];
